
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 760)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 761, 251))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 40, 91, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(120, 40, 134, 151))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lne_kurumismi = QtWidgets.QLineEdit(self.widget1)
        self.lne_kurumismi.setObjectName("lne_kurumismi")
        self.verticalLayout_3.addWidget(self.lne_kurumismi)
        self.lne_irtibatNo = QtWidgets.QLineEdit(self.widget1)
        self.lne_irtibatNo.setMaxLength(11)
        self.lne_irtibatNo.setObjectName("lne_irtibatNo")
        self.verticalLayout_3.addWidget(self.lne_irtibatNo)
        self.lne_gatewayId = QtWidgets.QLineEdit(self.widget1)
        self.lne_gatewayId.setObjectName("lne_gatewayId")
        self.verticalLayout_3.addWidget(self.lne_gatewayId)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(290, 40, 86, 121))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.txt_adress = QtWidgets.QLabel(self.widget2)
        self.txt_adress.setObjectName("txt_adress")
        self.verticalLayout_4.addWidget(self.txt_adress)
        self.spn_gatewayNo = QtWidgets.QSpinBox(self.groupBox)
        self.spn_gatewayNo.setGeometry(QtCore.QRect(380, 50, 71, 22))
        self.spn_gatewayNo.setObjectName("spn_gatewayNo")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(380, 130, 241, 101))
        self.textEdit.setObjectName("textEdit")
        self.lne_iletisim_mail = QtWidgets.QLineEdit(self.groupBox)
        self.lne_iletisim_mail.setGeometry(QtCore.QRect(380, 90, 191, 21))
        self.lne_iletisim_mail.setMaxLength(50)
        self.lne_iletisim_mail.setObjectName("lne_iletisim_mail")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 280, 891, 361))
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 650, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(200, 660, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(770, 10, 101, 251))
        self.widget3.setObjectName("widget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_ekle = QtWidgets.QPushButton(self.widget3)
        self.btn_ekle.setObjectName("btn_ekle")
        self.verticalLayout.addWidget(self.btn_ekle)
        self.btn_sil = QtWidgets.QPushButton(self.widget3)
        self.btn_sil.setObjectName("btn_sil")
        self.verticalLayout.addWidget(self.btn_sil)
        self.btn_ara = QtWidgets.QPushButton(self.widget3)
        self.btn_ara.setObjectName("btn_ara")
        self.verticalLayout.addWidget(self.btn_ara)
        self.btn_guncelle = QtWidgets.QPushButton(self.widget3)
        self.btn_guncelle.setObjectName("btn_guncelle")
        self.verticalLayout.addWidget(self.btn_guncelle)
        self.btn_listele = QtWidgets.QPushButton(self.widget3)
        self.btn_listele.setObjectName("btn_listele")
        self.verticalLayout.addWidget(self.btn_listele)
        self.btn_exit = QtWidgets.QPushButton(self.widget3)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 22))
        self.menubar.setObjectName("menubar")
        self.menuHakk_m_zda = QtWidgets.QMenu(self.menubar)
        self.menuHakk_m_zda.setObjectName("menuHakk_m_zda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_ayteam = QtWidgets.QAction(MainWindow)
        self.menu_ayteam.setObjectName("menu_ayteam")
        self.menu_fsm = QtWidgets.QAction(MainWindow)
        self.menu_fsm.setObjectName("menu_fsm")
        self.menuHakk_m_zda.addAction(self.menu_ayteam)
        self.menuHakk_m_zda.addAction(self.menu_fsm)
        self.menubar.addAction(self.menuHakk_m_zda.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "Kurum İsmi :"))
        self.label_3.setText(_translate("MainWindow", "İrtibat numarası :"))
        self.label_2.setText(_translate("MainWindow", "Gateway Id :"))
        self.label_5.setText(_translate("MainWindow", "İlçe :"))
        self.comboBox.setItemText(0, _translate("MainWindow", "İstanbul"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ankara "))
        self.comboBox.setItemText(2, _translate("MainWindow", "Kocaeli"))
        self.comboBox.setItemText(3, _translate("MainWindow", "İzmir"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Trabzon"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Bursa"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Eskişehir"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Antalya"))
        self.label_4.setText(_translate("MainWindow", "Gateway Sayısı :"))
        self.label_6.setText(_translate("MainWindow", "İletişim Maili : "))
        self.txt_adress.setText(_translate("MainWindow", "Kurum Adres :"))
        self.label_7.setText(_translate("MainWindow", "Toplam Kurum Sayısı : "))
        self.btn_ekle.setText(_translate("MainWindow", "Kurum Ekle"))
        self.btn_sil.setText(_translate("MainWindow", "Kurum Sil"))
        self.btn_ara.setText(_translate("MainWindow", "Kurum Ara"))
        self.btn_guncelle.setText(_translate("MainWindow", "Güncelle"))
        self.btn_listele.setText(_translate("MainWindow", "Kayıt Listele"))
        self.btn_exit.setText(_translate("MainWindow", "Çıkış"))
        self.menuHakk_m_zda.setTitle(_translate("MainWindow", "Hakkımızda"))
        self.menu_ayteam.setText(_translate("MainWindow", "FSM AYTEAM"))
        self.menu_fsm.setText(_translate("MainWindow", "Fatih Sultan Mehmet Üniversitesi"))
