# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces/home_interface/homeinterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icons
import iconss
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 668)
        MainWindow.setMinimumSize(QtCore.QSize(1202, 668))
        MainWindow.setMaximumSize(QtCore.QSize(1202, 668))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 651))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.widget.setFont(font)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1201, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("border-bottom-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"background-color: #8a2a2d;\n"
"color:#FFFFFF;\n"
"text-align: center;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, -20, 1201, 661))
        self.label_3.setMinimumSize(QtCore.QSize(1201, 661))
        self.label_3.setMaximumSize(QtCore.QSize(1201, 661))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-image: url(:/background/Dark Blue and Beige Experimental Art Deco PR Consultant Portfolio Website (1).png);\n"
"opacity: 0,52;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.btn_user = QtWidgets.QPushButton(self.widget)
        self.btn_user.setGeometry(QtCore.QRect(50, 280, 180, 180))
        self.btn_user.setStyleSheet("background-color: #8a2a2d;\n"
"border-image: url(:/icon/user.png);\n"
"border-radius:20;")
        self.btn_user.setText("")
        self.btn_user.setObjectName("btn_user")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(970, 280, 180, 180))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: #8a2a2d;\n"
"border-image: url(:/icon/big-data.png);\n"
"border-radius:20;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 280, 180, 180))
        self.pushButton_4.setStyleSheet("background-color: #8a2a2d;\n"
"\n"
"\n"
"border-radius:20;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(540, 310, 131, 131))
        self.label_4.setStyleSheet("border-image: url(:/icon/map.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 280, 181, 181))
        self.pushButton_2.setStyleSheet("background-color: #8a2a2d;\n"
"border-image: url(:/icon/4170461 (1) (1).png);\n"
"border-radius:20;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(510, 280, 180, 180))
        self.pushButton_9.setStyleSheet("background-color: #8a2a2d;\n"
"border-radius:20;")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(310, 310, 131, 121))
        self.label_5.setStyleSheet("border-image: url(:/icon/enterprise.png);\n"
"\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(60, 240, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #000000;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(300, 240, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #000000;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(520, 240, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #000000;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(760, 240, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #000000;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(990, 240, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #000000;")
        self.label_10.setObjectName("label_10")
        self.label_3.raise_()
        self.label.raise_()
        self.btn_user.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.pushButton_9.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "OTİZM BİLEKLİĞİ YÖNETİM SİSTEMİ"))
        self.label_6.setText(_translate("MainWindow", "Kullanıcılar"))
        self.label_7.setText(_translate("MainWindow", "Kurumlar"))
        self.label_8.setText(_translate("MainWindow", "Cihazları Bul"))
        self.label_9.setText(_translate("MainWindow", "Veri Arşivi"))
        self.label_10.setText(_translate("MainWindow", "Büyük Veri"))

